funfunsay/views/homesite.py
# -*- coding: utf-8 -*-

from uuid import uuid4
from datetime import datetime
import time

from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect, session, g, abort)
from jinja2 import TemplateNotFound
from werkzeug import check_password_hash, generate_password_hash
from funfunsay.forms import (SignupForm, LoginForm, RecoverPasswordForm,
                         ChangePasswordForm, ReauthForm)
from flaskext.babel import gettext as _
from flaskext.login import (login_required, login_user, current_user,
                            logout_user, confirm_login, fresh_login_required,
                            login_fresh)

from funfunsay.models import User
from funfunsay.extensions import cache, login_manager
from funfunsay.config import DefaultConfig, APP_NAME


homesite = Blueprint('homesite', __name__
                       #, url_prefix='/pl'
                       #,static_folder='/static'
                       )

@homesite.route('/')
def home():
    print current_app.config['FEATURE']
    if current_user.is_authenticated():
        return render_template('microblog/index.html' if current_app.config['FEATURE'] is 1 else 'index.html')

    login_form = signup_form = None
    if not current_user.is_authenticated():
        login_form= LoginForm(next=request.args.get('next'))
        signup_form = SignupForm(nex=request.args.get('next'))

    return render_template('microblog/index.html' if current_app.config['FEATURE'] is 1 else 'index.html', login_form=login_form,
                           signup_form=signup_form)


@homesite.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated, error = User.authenticate(form.login.data,
                                    form.password.data)

        if user and authenticated:
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):
                flash("Logged in!", 'success')
                session['user_id'] = user.id
            return redirect(form.next.data or url_for('homesite.home'))
        else:
            flash(_('Sorry, invalid login'), 'error')

    return render_template('login.html', form=form)


@homesite.route('/register', methods=['GET', 'POST'])
def register():
    login_form= LoginForm(next=request.args.get('next'))
    form = SignupForm(next=request.args.get('next'))

    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)

        user_doc = {"_id":form.name.data,
                    "email":form.email.data,
                    "pw_hash":generate_password_hash(form.password.data),
                    "copyrights":"user",
                    "reg_date":int(time.time())}
        g.db.users.insert(user_doc, safe=True)
        #todo: check fail
        flash('You were successfully registered and can login now')

        if login_user(user):
            return redirect(form.next.data or url_for('homesite.login'))

    return render_template('register.html', form=form, login_form=login_form)

@homesite.route('/logout')
def logout(): 
    """Logs the user out."""
    logout_user()
    flash('You were logged out')
    session.pop('user_id', None)
    return redirect(url_for('homesite.home'))

@homesite.route('/search')
def search():
    return render_template('search.html')

@homesite.route('/user_profile')
def user_profile():
    return render_template('uprofile.html')

funfunsay/views/microblog.py
# -*- coding: utf-8 -*-
"""
    FunFunSay
    ~~~~~~~~

    A micronoting application written with Flask and MongoDB.

    :copyright: (c) 2010 by Brent Jiang.
"""
import sys
import time
from contextlib import closing
from flask import (current_app, Blueprint, request, session, url_for, redirect, \
     render_template, abort, g, flash, jsonify)
from pymongo.objectid import ObjectId
import jinja2
import pymongo
from funfunsay.config import PER_PAGE
from flaskext.babel import gettext as _
from flaskext.login import (login_required, login_user, current_user,
                            logout_user, confirm_login, fresh_login_required,
                            login_fresh)

from funfunsay.models import User
from funfunsay.extensions import cache, login_manager

microblog = Blueprint('microblog', __name__, url_prefix='/m')


@microblog.route('/')
def timeline():
    """
    Index for FunFunSay Microblog.
    Shows a users timeline or if no user is logged in it will
    redirect to the public timeline.  This timeline shows the user's
    messages as well as all the messages of followed users.
    We need to use client-side linking since MongoDB doesn't support
    join operation (DBRefs is not a good choice here). Method get_username()
    is provided for such purpose.
    """
    if not current_user.is_authenticated():
        #print url_for('microblog.public_timeline')
        return redirect(url_for('microblog.public_timeline'))
    followers = []
    for f in g.db.followers.find({"who_id":session['user_id']},{"whom_id":1, "_id":0}):
        followers.append(f['whom_id'])
    messages = g.db.messages.find({"$or" : [{"author_id" : session['user_id']}, 
                                            {"author_id": {"$in" : followers}}], "host_id":None}, sort=[("pub_date",pymongo.DESCENDING)]).limit(PER_PAGE)
    return render_template('microblog/timeline.html', messages=messages)


@microblog.route('/public')
def public_timeline():
    """Displays the latest messages of all users."""
    messages = g.db.messages.find({"host_id":None}, sort=[('pub_date',pymongo.DESCENDING)]).limit(PER_PAGE)
    return render_template('microblog/timeline.html', messages=messages)


@microblog.route('/following')
@login_required
def my_following():
    """Displays the users or medias that i am following."""
    return render_template('microblog/timeline.html', messages=query_db('''
        select message.*, user.* from message, user
        where message.author_id = user.user_id
        order by message.pub_date desc limit ?''', [PER_PAGE]))

@microblog.route('/plaza')
def plaza():
    """Displays latest reviews, newly created media or users, hotest contents."""
    """latest messages"""
    messages = g.db.messages.find({"host_id":None}, sort=[("pub_date",pymongo.DESCENDING)]).limit(PER_PAGE)
    """newly created medias"""
    medias = g.db.users.find({"copyrights":{ "$ne":"user"}, "host_id":None}, sort=[("reg_date",pymongo.DESCENDING)]).limit(PER_PAGE)
    return render_template('plaza.html', messages=messages,medias=medias)

@microblog.route('/<username>')
def user_timeline(username):
    """Display's a users tweets."""
    profile_user_doc = g.db.users.find_one({"_id":username})
    if profile_user_doc is None:
        abort(404)
    followed = False
    if current_user.is_authenticated():
        followed = g.db.followers.find_one({"who_id":session['user_id'], "whom_id":username}) is not None
    messages = g.db.messages.find({"author_id":username, "host_id":None}, sort=[("pub_date",pymongo.DESCENDING)]).limit(PER_PAGE)
    return render_template('microblog/timeline.html', messages=messages, followed=followed,
            profile_user=profile_user_doc)


@microblog.route('/media/<medianame>')
def media(medianame):
    """Display's a medias tweets."""
    media_doc = g.db.users.find_one({"_id":medianame})
    if media_doc is None:
        abort(404)
    followed = False
    if current_user.is_authenticated():
        followed = g.db.followers.find_one({"who_id":session['user_id'], "whom_id":media_doc['_id']}) is not None
    contents = []
    for b in g.db.contents.find({"book_id":medianame}, {"_id":1}):
        contents.append(b['_id'])
    messages = g.db.messages.find({"content_id": {"$in":contents}, "host_id":None}, 
                                  sort=[("pub_date",pymongo.DESCENDING)]).limit(PER_PAGE)
    return render_template('media.html', messages=messages, 
                           followed=followed,
                           profile_media=media_doc)

			
@microblog.route('/<username>/follow')
@login_required
def follow_user(username):
    """Adds the current user as follower of the given user."""
    whom_id = username
    if whom_id is None:
        abort(404)
    follower_doc = {"who_id":session['user_id'], 
                    "whom_id":whom_id }
    g.db.followers.insert(follower_doc, safe=True)
    flash('You are now following "%s"' % username)
    return redirect(url_for('microblog.user_timeline', username=username))


@microblog.route('/<username>/unfollow')
@login_required
def unfollow_user(username):
    """Removes the current user as follower of the given user."""
    whom_id = username
    if whom_id is None:
        abort(404)
    g.db.followers.remove({"who_id":session['user_id'], 
                           "whom_id":whom_id }, safe=True)
    flash('You are no longer following "%s"' % username)
    return redirect(url_for('microblog.user_timeline', username=username))


@microblog.route('/add_message', methods=['POST'])
@login_required
def add_message():
    """Registers a new message for the user."""
    if request.form['text'] and request.form['text']<>'':
        #print request.form['text']
        message_doc = {"author_id":session['user_id'], 
                       "text":request.form['text'],
                       "pub_date":int(time.time()),
                       "content_id":None,
                       "host_id":None,
                       "score":0,
                       "vote_up_count":0,
                       "vote_down_count":0
                       }
        g.db.messages.insert(message_doc)
        flash('Your message was recorded')
    return redirect(url_for('microblog.timeline'))


@microblog.route('/reply_message', methods=['POST'])
@login_required
def reply_message():
    """Reply to a message(id=hostid)."""
    if request.form['text']:
        message_doc = {"author_id":session['user_id'], 
                       "text":request.form['text'],
                       "pub_date":int(time.time()),
                       "content_id":None,
                       "host_id":request.form['hostid'],
                       "score":0,
                       "vote_up_count":0,
                       "vote_down_count":0
                       }
        g.db.messages.insert(message_doc)
        flash('Your reply was recorded')
    return redirect(url_for('microblog.timeline'))

	
@microblog.route('/create', methods=['GET', 'POST'])
@login_required
def create_media():
    """Create a media is like registers the user."""
    error = None
    if request.method == 'POST':
        if not request.form['username']:
            error = 'You have to enter a username'
        elif not request.form['email'] or \
                 '@' not in request.form['email']:
            error = 'You have to enter a valid email address'
        elif not request.form['copyrights']:
            error = 'You have to enter copyrights information'
        elif g.db.users.find_one({'_id':request.form['username']}) is not None:
            error = 'The media is already existing.'
        else:
            user_doc = {"_id":request.form['username'],
                        "email":request.form['email'],
                        "pw_hash":generate_password_hash("default"),
                        "copyrights":request.form['copyrights'],
                        "reg_date":int(time.time())}
            g.db.users.insert(user_doc, safe=True)
            #todo: check fail
            flash('Media creation application was successfully applied and can now to be remarked')
            return redirect(url_for('microblog.media', medianame=request.form['username']))
    return render_template('microblog/create.html', error=error)


@microblog.route('/_get_replies')
def get_replies():
    messageid = request.args.get('messageid')
    messages = g.db.messages.find({"host_id":messageid}, sort=[("pub_date", pymongo.DESCENDING)]).limit(PER_PAGE)
    return jsonify(result=jinja2.Markup(render_template("microblog/replies_widget.html", replies=messages, hostid=messageid)))

@microblog.route('/m/_get_new_message')
@login_required
def get_new_message():
    if not current_user.is_authenticated():
        g.my_new_message = None
        return jsonify(messageid="", messagepubdate="", imgsrc="")
    else:
        g.my_new_message = get_latest_message(current_user.id)
        #print g.my_new_message
        return jsonify(messageid="%s"%g.my_new_message['_id'], messagepubdate=format_datetime(g.my_new_message['pub_date']),
                       imgsrc=gravatar_url(current_user.email, 48))

# get the new reply that current user posted
@microblog.route('/_get_new_reply')
@login_required
def get_new_reply():
    g.my_new_message = get_latest_message(current_user.id)
    #print g.my_new_message
    return jsonify(hostid="%s"%g.my_new_message['host_id'],
                    messageid="%s"%g.my_new_message['_id'], messagepubdate=format_datetime(g.my_new_message['pub_date']),
                    imgsrc=gravatar_url(current_user.email, 48))

@microblog.route('/_vote')
@login_required
def vote():
    messageid = ObjectId(request.args.get('messageid'))
    voteval = int(request.args.get('voteval'))
    if not current_user.is_authenticated():
        return jsonify(result=0)

    voteresult, score = User.do_vote(messageid, voteval)
    return jsonify(result=1, voteresult=voteresult, score=score, messageid = request.args.get('messageid'))

funfunsay/templates/microblog/_layout.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Welcome{% endblock %} | FunFunSay</title>
    <meta name="author" content="Brent Jiang">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-responsive.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.js') }}"></script>
    <script type="text/javascript">
      var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
</head>
<body style="padding-top: 40px;" data-spy="scroll" data-target=".subnav" data-offset="50">
  <!-- Navbar
    ================================================== -->
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
                    class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                </a><a class='brand' href="{{ url_for('homesite.home') }}">FUNFUNSAY</a>
                <div class="nav-collapse">
                    <ul class="nav">
                        <li class="active"><a href="#" id="homeToSubsite">{{_("Home")}}</a></li>
                        <!--<li><a href="#about">{{_("About")}}</a></li>
                        <li><a href="#contact">{{_("Contact us")}}</a></li>-->
                    </ul>
<!--                    <form class="navbar-search pull-left">
                        <input type="text" class="search-query" placeholder="Search">
                    </form>
-->

                <!--user login control-->
                    {% if current_user.is_authenticated() %}
                    <ul class="nav pull-right">
                        <li class="divider-vertical"/>
                        <li class="dropdown">
                            <!--{{_("Logged in as")}}--><a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ current_user.name }}<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('homesite.user_profile') }}">{{_("User Profile")}}</a></li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for('homesite.logout') }}">{{_("Logout")}}</a></li>
                            </ul>
                        </li>
                    </ul>
                    <p class="navbar-text pull-right">
                        {{_("Logged in as")}}</p>
                    {% elif login_form is defined %}
                    <form class='navbar-form pull-right' method='POST' action="{{ url_for('homesite.login') }}">
                        {{ login_form.hidden_tag() }}
                        {{ login_form.next }}
                        {{ login_form.login(class_='input-small', placeholder='Username') }}
                        {{ login_form.password(class_='input-small', placeholder='Password') }}
                        <button type="submit" class="btn btn-primary btn-small">{{_("Log in")}}</button>
                    </form>
                    {% endif %}
                 <!--/user login control-->
                                 </div>
                <!--/.nav-collapse -->
           </div>
        </div>
    </div>

    <!-- Masthead
    ================================================== -->
    <div class="container">
        <header class="jumbotron subhead" id="overview">{% block header %}{% endblock %}</header>
        <section id="microblogNav">
            <div class=navigation>
            {% if current_user.is_authenticated() %}
                <a href="{{ url_for('microblog.timeline') }}">my timeline</a> |
                <a href="{{ url_for('microblog.public_timeline') }}">public timeline</a> |
                <a href="{{ url_for('homesite.logout') }}">sign out [{{ current_user.id }}]</a>
            {% else %}
                <a href="{{ url_for('microblog.public_timeline') }}">public timeline</a> |
                <a href="{{ url_for('homesite.register') }}">sign up</a> |
                <a href="{{ url_for('homesite.login') }}">sign in</a>
            {% endif %}
            </div>
        </section>
        <section id="flashesDisplay">
            {% with flashes = get_flashed_messages() %} {% if flashes %}
            <ul class="flashes">
                {% for message in flashes %}
                <li>
                {{ message }} {% endfor %}
            </ul>
            {% endif %} {% endwith %}
        </section>
        <section id="bodySection">{% block body %}{% endblock %}</section>
        <br />

        <footer class="footer">
            <p class="pull-right"><a href="#">Back to top</a></p>
            <div class="span8">
            <img src="{{url_for('static', filename='img/microblog.png')}}" alt="miiBlog"/>
            <h3><small>
            It's a miiBlog site!</small>
            </h3>
            </div>
        </footer >
    </div>

    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-collapse.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-dropdown.js') }}"></script>

    {% block script %}
    {% endblock %}

</body>

funfunsay/templates/microblog/index.html
{% extends 'microblog/_layout.html' %}

{% block title %}
  {{_("miiBlog")}}
{% endblock %}

{% block body %}
<div class="hero-unit">
    <h1><a href="/m">{{_("miiBlog")}}</a></h1>
    <h2><small>{{_("It's a Microblog! Share your ideas!")}}</small></h2>
</div>
{% endblock %}

{% block script %}
{% endblock %}

funfunsay/templates/microblog/replies_widget.html
<div class="replybox">
    <form class="replyform" id="replyform{{hostid}}" action="{{ url_for('microblog.reply_message') }}"
    method="post">
    <p>
        <textarea class="newreply" id="newreply{{hostid}}" name="text"></textarea>
        <input type="hidden" name="hostid" value="{{hostid}}" />
        <!--
          -->
        <input type="submit" value="Reply">
    </form>
    <ul class="replies" id="replies{{hostid}}">
        {% for message in replies %}
        <li>
            <img src="{{ g.get_user(message.author_id).email|gravatar(size=48)}}"><p>
                <strong><a href="{{ url_for('microblog.user_timeline', username=message.author_id)
    }}">{{ message.author_id }}</a></strong> {{ message.text }} <small>&mdash; {{ message.pub_date|datetimeformat
        }}</small> {% if current_user.is_authenticated() %}
                <p align="right" style='text-align: right'>
                    <small><a href="#" id="reply">Reply</a></small></p>
        {% endif %} {% else %} {% endfor %}
    </ul>
</div>
<script type="text/javascript">
    // wait for the DOM to be loaded
    $(document).ready(function () {
        var options = {
            beforeSubmit: validateNewReply,
            success: prependReply
        };

        $(".replyform").ajaxForm(options);
    });

    function validateNewReply(formData, jqForm, options) {
        var form = jqForm[0];
        if (!form.text.value) {
            //alert('not null!');
            return false;
        }

        return true;
    }

    function prependReply(responseText, statusText) {
        //alert(responseText);
        // GET NEWEST REPLY ID THAT I POST 
        // DOESN'T INCLUDE OTHER USER'S REPLY TO THIS MESSAGE
        $.getJSON($SCRIPT_ROOT + '/_get_new_reply', function (data) {
            var hostid = data.hostid;
            var messageid = data.messageid;
            var messagepubdate = data.messagepubdate;
            var imgsrc = data.imgsrc;
            var div = document.createElement("div");
            div.innerHTML = "<li><img src='" + imgsrc + "'><p> " +
                    "<strong><a href='{{url_for('microblog.user_timeline', username=current_user.id)}}'>{{ current_user.id}}</a></strong>&nbsp; " + $('#newreply' + hostid).val()
                    + "<small>&mdash; " + messagepubdate + "</small><p align='right' style='text-align: right'><small><a href='#' data-messageid='#comments" + messageid + "' class='comment'>Reply</a></small></p><p><br /><div class='comments hidden' id='comments" + messageid + "'></div></p></p></li>";
            //alert('ul#replies'+hostid);
            $('ul#replies' + hostid).prepend(div);
            $('textarea#newreply' + hostid).val('');
        });
        return false;
    }
</script>

funfunsay/templates/microblog/timeline.html
{% extends "microblog/_layout.html" %}
{% block title %} 
{% if request.endpoint=='microblog.public_timeline' %} 
Public Timeline 
{% elif request.endpoint == 'microblog.user_timeline'%}
{{ profile_user._id }}'s Timeline 
{% else %}
My Timeline 
{% endif %}
{% endblock%}


{% block body %}
<h2>
    {{ self.title() }}</h2>
{% if current_user.is_authenticated() %}
{% if request.endpoint == 'microblog.user_timeline'%}
<div class="row">
    {% if current_user.id == profile_user._id %}
    This is you!
    {% elif followed %}
    You are currently following this user. 
    <a class="unfollow" href="{{ url_for('microblog.unfollow_user', username=profile_user._id)}}">Unfollow user</a>. 
    {% else %} 
    You are not yet following this user. 
    <a class="follow" href="{{ url_for('microblog.follow_user', username=profile_user._id)}}">Follow user</a>. 
    {% endif %}
</div>
{% elif request.endpoint == 'microblog.timeline' %}
<div class="twitbox">
    <h3>
        What's on your mind {{ current_user.id }}?</h3>
    <form id="messageForm" action="{{url_for('microblog.add_message')}}" method="post">
    <p>
        <textarea id="newMessage" name="text"></textarea><!--
          --><input type="submit" value="Share" /></p>
    </form>
</div>
{% endif %} {% endif %}
<ul class="messages" id="messages">
    {% for message in messages %}
    <li>
        <table style="width: 100%">
            <tbody>
                <tr>
                    <td style="width: auto">
                        <div class="vote">
                            {% set messagevote=message._id|myvote %} {% if messagevote != 0 %}
                            <img id="message-img-upvote-{{ message._id }}" class="message-img-upvote" src="/static/vote-arrow-up{% if messagevote==1 %}-on{% endif %}.png"
                                title="i like this post (click again to cancel)" />
                            <div id="message-vote-number-{{ message._id }}" class="vote-number" title="current score of votes">
                                {{ message.score|scoreformat }}
                            </div>
                            <img id="message-img-downvote-{{ message._id }}" class="message-img-downvote" src="/static/vote-arrow-down{% if messagevote==-1 %}-on{% endif %}.png"
                                title="i dont like this post (click again to cancel)" />
                            {% else %}
                            <img id="message-img-upvote-{{ message._id }}" class="message-img-upvote" src="/static/vote-arrow-up.png"
                                title="i like this post (click again to cancel)" />
                            <div id="message-vote-number-{{ message._id }}" class="vote-number" title="current score of votes">
                                {{ message.score|scoreformat }}
                            </div>
                            <img id="message-img-downvote-{{ message._id }}" class="message-img-downvote" src="/static/vote-arrow-down.png"
                                title="i dont like this post (click again to cancel)" />
                            {% endif %}
                        </div>
                    </td>
                    <td style="width: 100%">
                        <img src="{{ message.author_id|user_email|gravatar(size=48)}}">
                        <p>
                            <strong><a href="{{ url_for('microblog.user_timeline', username=message.author_id)}}">
                                {{ message.author_id}}</a></strong>&nbsp; {{ message.text }}<small>&mdash; {{ message.pub_date|datetimeformat}}</small>
                            {% if current_user.is_authenticated() %}
                            <p align="right" style='text-align: right'>
                                <small><a href="#" data-messageid="#replies{{message._id}}" class="reply">Reply</a></small></p>
                            {% endif %}
                        </p>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                        <p>
                            <br />
                            <div class="replies hidden" id="replies{{message._id}}">
                            </div>
                        </p>
                    </td>
                </tr>
            </tbody>
        </table>
    </li>
    {% else %}
    <li><em>There's no message so far.</em></li>
    {% endfor %}
</ul>
{% block script %}
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.form.js') }}"></script>
<script type="text/javascript">
    // wait for the DOM to be loaded
    $(document).ready(function () {
        $("#messageForm").ajaxForm(function () {
            // GET NEWEST MESSAGE ID
            $.getJSON($SCRIPT_ROOT + '/_get_new_message', function (data) {
                var messageid = data.messageid;
                var messagepubdate = data.messagepubdate;
                var imgsrc = data.imgsrc;
                //alert(messageid); //TESTED! the messageid is the newly added message's _id!
                var div = document.createElement("div");
                div.innerHTML = "<li><img src='" + imgsrc + "'><p> " +
                         "<strong><a href='{{url_for('microblog.user_timeline', username=current_user.id)}}'>{{ current_user.id}}</a></strong>&nbsp; " + $('#newMessage').val()
                         + "<small>&mdash; " + messagepubdate + "</small><p align='right' style='text-align: right'><small><a href='#' data-messageid='#replies" + messageid + "' class='reply'>Reply</a></small></p><p><br /><div class='replies hidden' id='replies" + messageid + "'></div></p></p></li>";
                $('ul#messages').prepend(div);
                $('#newMessage').val('');
            });
            return false;
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.messages').unbind('click');
        $('.messages').on('click', 'a.reply', function (event) {
            messageid = $(this).attr('data-messageid');
            $(messageid).html('loading');
            $.getJSON($SCRIPT_ROOT + '/m/_get_replies', { messageid: messageid.substring(8) }, function (data) {
                $(messageid).html(data.result);
                $(messageid).slideToggle(0);
            });
            return false;
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $(".message-img-upvote").unbind('click');//@faq: this is a work around. but why jQuery trigger twice here if without unbind?
        $('.message-img-upvote').click(function (evt) {
            var messageid = $(this).attr("id").substring(19);
            //alert(messageid);
            $.getJSON($SCRIPT_ROOT + '/m/_vote', { messageid: messageid, voteval: 1 }, function (data) {
                if (data.result == 0)
                    return false;
                // alert($(this).attr("id"));//will print "undefined"!!!
                if (data.voteresult == 0) {
                    //the first lines ensure image reload
                    //var d = new Date();
                    //$("#message-img-upvote-" + messageid).attr("src", "/static/vote-arrow-up.png?timestamp=" + d.getTime()); // without removeAttr("src")
                    //$("#message-img-downvote-" + messageid).removeAttr("src").attr("src", "/static/vote-arrow-down.png?timestamp=" + d.getTime());
                    $("#message-img-upvote-" + messageid).attr("src", "/static/vote-arrow-up.png");
                    $("#message-img-downvote-" + messageid).attr("src", "/static/vote-arrow-down.png");
                } else if (data.voteresult == 1) {
                    $("#message-img-upvote-" + messageid).attr("src", "/static/vote-arrow-up-on.png");
                    $("#message-img-downvote-" + messageid).attr("src", "/static/vote-arrow-down.png");
                }
                $("#message-vote-number-" + messageid).html(data.score);
            });
        });
        $(".message-img-downvote").unbind('click');
        $('.message-img-downvote').click(function (evt) {
            var messageid = $(this).attr("id").substring(21);
            //alert(messageid);
            $.getJSON($SCRIPT_ROOT + '/m/_vote', { messageid: messageid, voteval: -1 }, function (data) {
                if (data.result == 0)
                    return false;
                if (data.voteresult == 0) {
                    $("#message-img-upvote-" + messageid).attr("src", "/static/vote-arrow-up.png");
                    $("#message-img-downvote-" + messageid).attr("src", "/static/vote-arrow-down.png");
                } else if (data.voteresult == -1) {
                    $("#message-img-upvote-" + messageid).attr("src", "/static/vote-arrow-up.png");
                    $("#message-img-downvote-" + messageid).attr("src", "/static/vote-arrow-down-on.png");
                }
                $("#message-vote-number-" + messageid).html(data.score);
            });
        });
    });
</script>
{% endblock %} {% endblock %} 